### ISSUE TITLE
[Bug] Plugin just literally doesn't work

### ISSUE THREAD

**Issue by firinael** [artisticat1/obsidian-latex-suite#11]
None of the plugin's functions work, from the snippets to tabout, nothing. Tried a bunch of stuff already (disabling other plugins, reinstalling, etc.), to no avail. All I've got that *might* lead to a solution is these errors Obsidian throws up:

```app.js:1 Command failed to execute:  obsidian-latex-suite:latex-suite-box-equation
app.js:1 TypeError: Cannot read properties of undefined (reading 'main')
    at isWithinMath (eval at <anonymous> (app.js:1:1494667), <anonymous>:1444:36)
    at Object.editorCheckCallback (eval at <anonymous> (app.js:1:1494667), <anonymous>:4806:26)
    at Object.e.mobileOnly.xb.isMobile.e.checkCallback (app.js:1:1618478)
    at app.js:1:1619065
    at Array.filter (<anonymous>)
    at e.listCommands (app.js:1:1619003)
    at e.getCommands (app.js:1:1662005)
    at t.getItems (app.js:1:1663065)
    at t.getSuggestions (app.js:1:1469819)
    at t.updateSuggestions (app.js:1:1469049)
(anonymous) @ app.js:1
app.js:1 Command failed to execute:  obsidian-latex-suite:latex-suite-select-equation
app.js:1 TypeError: Cannot read properties of undefined (reading 'main')
    at isWithinMath (eval at <anonymous> (app.js:1:1494667), <anonymous>:1444:36)
    at Object.editorCheckCallback (eval at <anonymous> (app.js:1:1494667), <anonymous>:4830:26)
    at Object.e.mobileOnly.xb.isMobile.e.checkCallback (app.js:1:1618478)
    at app.js:1:1619065
    at Array.filter (<anonymous>)
    at e.listCommands (app.js:1:1619003)
    at e.getCommands (app.js:1:1662005)
    at t.getItems (app.js:1:1663065)
    at t.getSuggestions (app.js:1:1469819)
    at t.updateSuggestions (app.js:1:1469049)
(anonymous) @ app.js:1
app.js:1 Command failed to execute:  obsidian-latex-suite:latex-suite-box-equation
app.js:1 TypeError: Cannot read properties of undefined (reading 'main')
    at isWithinMath (eval at <anonymous> (app.js:1:1494667), <anonymous>:1444:36)
    at Object.editorCheckCallback (eval at <anonymous> (app.js:1:1494667), <anonymous>:4806:26)
    at Object.e.mobileOnly.xb.isMobile.e.checkCallback (app.js:1:1618478)
    at app.js:1:1619065
    at Array.filter (<anonymous>)
    at e.listCommands (app.js:1:1619003)
    at e.getCommands (app.js:1:1662005)
    at t.getItems (app.js:1:1663065)
    at t.getSuggestions (app.js:1:1469819)
    at t.updateSuggestions (app.js:1:1469049)
(anonymous) @ app.js:1
app.js:1 Command failed to execute:  obsidian-latex-suite:latex-suite-select-equation
app.js:1 TypeError: Cannot read properties of undefined (reading 'main')
    at isWithinMath (eval at <anonymous> (app.js:1:1494667), <anonymous>:1444:36)
    at Object.editorCheckCallback (eval at <anonymous> (app.js:1:1494667), <anonymous>:4830:26)
    at Object.e.mobileOnly.xb.isMobile.e.checkCallback (app.js:1:1618478)
    at app.js:1:1619065
    at Array.filter (<anonymous>)
    at e.listCommands (app.js:1:1619003)
    at e.getCommands (app.js:1:1662005)
    at t.getItems (app.js:1:1663065)
    at t.getSuggestions (app.js:1:1469819)
    at t.updateSuggestions (app.js:1:1469049)
(anonymous) @ app.js:1
```

EDIT: I'm using trying to use the default snippets.

**Comment by artisticat1** [comment]
Are you using the legacy editor? The plugin is written for the new CM6 editor only. I'll add a notice for this in the README and inside the plugin itself.

**Comment by firinael** [comment]
Yeah I'm using legacy, shame it doesn't work on it. Guess I'll just have to stick to espanso.

________________________________
De: artisticat1 ***@***.***>
Enviado: quinta-feira, 21 de abril de 2022 06:25
Para: artisticat1/obsidian-latex-suite ***@***.***>
Cc: firinael ***@***.***>; Author ***@***.***>
Assunto: Re: [artisticat1/obsidian-latex-suite] [Bug] Plugin just literally doesn't work (Issue #11)


Are you using the legacy editor? The plugin is written for the new CM6 editor only. I'll add a notice for this in the README and inside the plugin itself.

**Comment by artisticat1** [comment]
Yeah. Due to big differences in how the old and new editors work, it'd be too difficult for me to maintain support for the legacy editor, unfortunately. Apologies!
