### ISSUE TITLE
[BUG] Proposed Fix To Errors When Using Codeblock Math Mode

### ISSUE THREAD

**Issue by WhoAmI-WhereAmI** [artisticat1/obsidian-latex-suite#316]
# Description
currently, when using codeblocks, latex suite constantly warns:
`plugin:obsidian-latex-suite:13223 unable to locate start of the codeblock even though inside one`

also, when putting `math` as codeblock language, it now errs:
`TypeError: Cannot read properties of null (reading 'from')
    at getCodeblockBounds (plugin:obsidian-latex-suite:13211:52)
    at _Context.getInnerBounds (plugin:obsidian-latex-suite:13133:16)
    at _Context.isWithinEnvironment (plugin:obsidian-latex-suite:13082:25)
    at _Context.inTextEnvironment (plugin:obsidian-latex-suite:13114:17)
    at _Context.fromState (plugin:obsidian-latex-suite:13071:30)
    at _Context.fromView (plugin:obsidian-latex-suite:13077:21)
    at handleKeydown (plugin:obsidian-latex-suite:15237:23)
    at Object.onKeydown (plugin:obsidian-latex-suite:15231:19)
    at app.js:1:375614
    at e.runHandlers (app.js:1:373670)`

# To Reproduce
also happens in sandbox vault with only latex suite downloaded.

# Expected Behavior
should be able to locate codeblock properly

# Additional Info
in main.js file of latex suite plugin, function `escalateToToken` is the cause of error.
the fix is to search for `HyperMD-codeblock_HyperMD-codeblock-bg` instead of `HyperMD-codeblock_HyperMD-codeblock-begin`
at line 13212 and 13225.
supposedly obsidian itself has changed the name at some point...?
however, doing this somehow hinders the friendly popup equation and it won't work now.
if sbd with any idea what's going on can leave a comment that'd be awesome

**Comment by superle3** [comment]
> in main.js file of latex suite plugin, function escalateToToken is the cause of error.
the fix is to search for HyperMD-codeblock_HyperMD-codeblock-bg instead of HyperMD-codeblock_HyperMD-codeblock-begin
at line 13212 and 13225.
supposedly obsidian itself has changed the name at some point...?

No they haven't, the full name of the backticks node is `HyperMD-codeblock_HyperMD-codeblock-begin_HyperMD-codeblock-begin-bg_HyperMD-codeblock-bg`.
It's just that instead of being **inside** a codeblock syntaxnode (cause why not obsidian...), the syntax nodes are only placed at the backticks themselves. We resolve by using a treecursor, but when the cursors is at a newline or right at the backticks the cursor doesn't go over them and we haven't fixed that edge case yet.

Edit: 
There are still 3 prs open not from me and they have been open for long time without review, 
so I first want to give them a chance to respond before I merge anything significant.
