### ISSUE TITLE
Mobile support does not seem to work

### ISSUE THREAD

**Issue by eliazar-sll** [artisticat1/obsidian-latex-suite#52]
The support for mobile (android) doesn't seem to work. 

![Recording](https://user-images.githubusercontent.com/75558018/189464866-f1ef0cad-9b47-40a6-bb53-5a5486a104d9.gif)

I tried it on both of my android devices but neither of them worked. I checked if other plug-ins caused that, so I made a fresh obsidian installation but it still has no effect.

**Additional Details:**
- Live Preview editor is enabled
- Lastest version is installed
- Android version: 12

**Comment by artisticat1** [comment]
I don't have an Android device so I can't easily debug this.

- Can you paste your debug info here? (Command palette -> Show debug info)
- Do other features of the plugin work (conceal, color matching brackets)?
- Does an older version of the plugin work? Try v1.3.0, it's the earliest version that is compatible with Obsidian v0.15 and newer. You can install older versions of the plugin using BRAT.

**Comment by eliazar-sll** [comment]
Sure, can do that.

**This is the debug info:**
```
SYSTEM INFO:
	Operating system: android 12 (vivo V2038)
	Obsidian version: 1.3.1 (65)
	API version: v0.15.9
	Login status: not logged in
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Latex Suite v1.4.3

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

Next, I can confirm that the conceal and color matching brackets are working.
![Screenshot_2022_0910_202751](https://user-images.githubusercontent.com/75558018/189483403-96f5156a-572c-46a3-b7de-1096009a8639.jpg)

Lastly, The v1.3.0 didn't work, even the v1.4.0 to v1.4.2 had no luck.

**Trying v1.3.0:**
<img src="https://user-images.githubusercontent.com/75558018/189483964-c112ea1c-5c99-4d01-be4d-2f220e40d5c1.gif" height="700">

**Comment by artisticat1** [comment]
I see. The fact that the conceal and color matching brackets features are working means that the plugin is loading correctly, and CodeMirror extensions are working.

- Do the auto-fraction, matrix shortcuts, and tabout features work?
- Are you using the default snippets?
- Could you install this dev tools plugin ([https://github.com/KjellConnelly/obsidian-dev-tools](https://github.com/KjellConnelly/obsidian-dev-tools)) with BRAT? This will give us access to a console on mobile.
  After enabling the plugin, open a console using the Command palette. Then let me know whether you see any errors in the console when you enable Latex Suite, and when you try typing snippets.

**Comment by eliazar-sll** [comment]
Yes, I'm using the default snippets. In fact, I just discovered it then I found this issue. Unfortunately, I'm afraid auto-fraction, matrix shortcuts, and tabout features are not working. 

**Trying the said features with the dev tools console opened.**
![Screenrecording_20220911_170346](https://user-images.githubusercontent.com/75558018/189520795-3710f209-3ffc-4060-9b31-d4b1b368d4ce.gif)

As you can see, I received no error while testing the features. Please let me know if you need further testing.

**Comment by artisticat1** [comment]
Hmm I see. Do you get any errors when you first enable the Latex Suite plugin?

It does seem strange that you get no errors. Please give me some time to put together a debug build and get back to you!

**Comment by eliazar-sll** [comment]
> Do you get any errors when you first enable the Latex Suite plugin?

Sorry for the late reply. It sure was strange but I just double checked it, and I really didn't saw any errors after I enabled the Latex suite plug-in.

**Comment by proItheus** [comment]
@eliazar-sll Have you noticed the **underline** on what you typed?  I think this is a problem about your input method . When you are typing ,  the input method actually hold the letters without passing it to obsidian . Only after you select a word or press something like `space` will it pass the letters you typed **all at the same time** to obsidian, and the underline disaopears . You can try to use some input methods that directly pass your input to the target app ,`hacker's keyboard` etc.

**Comment by eliazar-sll** [comment]
Your suggestion sounds very promising so I tried it with 2 different keyboards, each disabled their autocomplete functionalities

**Hacker's Keyboard:**
https://user-images.githubusercontent.com/75558018/193431699-5729f240-0e3e-4aee-9df0-acad180ba2b4.mp4

**Simple Keyboard:**
https://user-images.githubusercontent.com/75558018/193431711-b8cd93ab-ae18-4db9-b5db-415c7ff4831f.mp4

And as you can see, the underline disappeared but the problem still persists. Do you have any thoughts about this?

**Comment by proItheus** [comment]
Ah, It's a bit strange. I tried it by myself, and find almost all input methods on android won't work with latex suite... However, [trime](https://github.com/osfans/trime) does work for me.  I have no clue about why they work or not work though. Maybe something about input key event?

**Comment by artisticat1** [comment]
I've put together this debug build. It prints some console.log statements whenever the plugin detects a keypress.

[obsidian-latex-suite-1.6.0-debug.zip](https://github.com/artisticat1/obsidian-latex-suite/files/9792052/obsidian-latex-suite-1.6.0-debug.zip)

Can any android users test this build and upload a video of what appears in the console? It would be helpful if you did this using the different keyboards that do/do not work, described by @proItheus above.

**Comment by proItheus** [comment]
Sorry but how can I enable the `consloe` on obsidian android?

**Comment by eliazar-sll** [comment]
@proItheus Quoting from @artisticat1, I think this is the process of enabling `console` on obsidian
> Could you install this dev tools plugin (https://github.com/KjellConnelly/obsidian-dev-tools) with BRAT? This will give us access to a console on mobile.
> - After enabling the plugin, open a console using the Command palette. Then let me know whether you see any errors in the console when you enable Latex Suite, and when you try typing snippets.

**Comment by eliazar-sll** [comment]
@artisticat1, I just tried the debug build and it logs `The "Unidentified" key was pressed` every time I press a key

**Keyboard:** Microsoft G-swift
![video_20221015_212115_edit](https://user-images.githubusercontent.com/75558018/195988862-c579389d-5728-4a9b-84f8-b99751ef0d5b.gif)

**Comment by proItheus** [comment]
Confirmed that the plugin logs keydown normally for the `trime` keyboard mentioned above, while loging `Unidentified key` as @eliazar-sll finds for keyboards not working , that is , almost all other keyboards I can find for android ...

**Comment by artisticat1** [comment]
Thank you both! It appears that keypresses are not being transferred to the plugin correctly. I'll try to investigate this further.

**Comment by artisticat1** [comment]
Can you visit https://codemirror.net/try/ and paste the following code into the editor on the left hand side?

```javascript
import {minimalSetup, EditorView} from "codemirror"
import {Prec} from "@codemirror/state";

const onKeydownExtension = Prec.highest(EditorView.domEventHandlers({
    "keydown": (event, view) => {
      console.log("The " + event.key + " key was pressed.");
    }
}));

new EditorView({
  doc: "...",
  extensions: [minimalSetup, onKeydownExtension],
  parent: document.body
})

```
(Erase the code contained in the editor by default.)

This code will set up a test editor with a debug statement that prints out keypresses the editor detects. Press the "Run" button after pasting in the code in order to initialise the test editor (which sits on the right hand side).

Then, in the editor on the right, type in some text. Then switch to the "Log" tab and let me know what it says.

**Comment by eliazar-sll** [comment]
Just tried it and this is the screen recording.
![Record_2022-10-31-17-14-10.gif](https://user-images.githubusercontent.com/75558018/198974402-bf76986f-fb29-4f13-ac7b-2b433df3f86e.gif)

And these are the logs, I noticed that it only detects the backspace and numerical keys.
```
The Unidentified key was pressed.
The Backspace key was pressed.
The Unidentified key was pressed.
The Backspace key was pressed.
The Unidentified key was pressed.
The Backspace key was pressed.
The Unidentified key was pressed.
The Unidentified key was pressed.
The Unidentified key was pressed.
The Unidentified key was pressed.
The Unidentified key was pressed.
The Unidentified key was pressed.
The Unidentified key was pressed.
The Unidentified key was pressed.
The Unidentified key was pressed.
The Backspace key was pressed.
The Unidentified key was pressed.
The Backspace key was pressed.
The Unidentified key was pressed.
The Backspace key was pressed.
The Unidentified key was pressed.
The Backspace key was pressed.
The Unidentified key was pressed.
The Backspace key was pressed.
The Unidentified key was pressed.
The Backspace key was pressed.
The Unidentified key was pressed.
The Backspace key was pressed.
The 4 key was pressed.
The 8 key was pressed.
The 7 key was pressed.
The 4 key was pressed.
The 6 key was pressed.
The Unidentified key was pressed.
The Backspace key was pressed.
The Unidentified key was pressed.
The Backspace key was pressed.
The Unidentified key was pressed.
The Backspace key was pressed.
The Unidentified key was pressed.
The Backspace key was pressed.
The Unidentified key was pressed.
The Backspace key was pressed.
The Unidentified key was pressed.
The Unidentified key was pressed.
The Unidentified key was pressed.
The Backspace key was pressed.
The Unidentified key was pressed.
The Backspace key was pressed.
The Unidentified key was pressed.
The Unidentified key was pressed.
The Unidentified key was pressed.
The Backspace key was pressed.
The Unidentified key was pressed.
The Backspace key was pressed.
```

**Comment by L0L1P0P1** [comment]
>  try using some input methods that directly pass your input to the target app ,`hacker's keyboard` etc.
LaTex suite seems to work in android with an external keyboard. Yet it doesn't work at all in other circumstances.

**Comment by awsharif** [comment]
Hi @artisticat1, has there been any further investigation about this?

**Comment by artisticat1** [comment]
> Hi @artisticat1, has there been any further investigation about this?

I think it's some sort of issue with CodeMirror not receiving key-press events from Android keyboards.

I don't think there's much I can do on my side, except possibly look for a workaround.

**Comment by oldkingOK** [comment]
Hi @Deadbush225 ,I found a solution.
When a key on the keyboard is clicked , the Obsidian can't detect key exactly because of IME (means Input-Method Editor) which almost every common keyboard app has.
(See [event.key = Unidentified, event.keyCode = 229 #14512](https://github.com/facebook/react/issues/14512) for more information)
Only when we use some unusual keyboard apps without IME can the obsidian detect the exact key, the only one I know of which is "Game Keyboard+", but this one can't be used to type any letter, so we need a physical keyboard to do it.

Specific methods are as follows:
1. Download ,install and start "Game Keyboard+" app on mobile.
2. Follow the instruction Step 1 2 and 3.
3. Click "Custom & Test" and delete all keys because we don't need them.
4. Connect the physical keyboard to the mobile.
5. Go to Obsidian and have a try.
![Screenrecorder](https://user-images.githubusercontent.com/30453803/222880627-b2229822-ce61-499f-ba36-63c0de04b3d9.gif)

(This solution will be better if someone found a common keyboard without IME)
I'm a novice in writing English sentences and using Obsidian, any suggestion is welcome.

**Comment by pikatwinky** [comment]
Has anybody found a workaround to this?

**Comment by TomBPotochek** [comment]
@pikatwinky it is working for me. I'm using [codeboard](https://play.google.com/store/apps/details?id=com.gazlaws.codeboard). I believe the problem was solved when obsidian migrated to codemirror6 but I'm wildly guessing.  
I think this issue can be closed.

**Comment by TomBPotochek** [comment]
@oldkingOK have you tried using codeboard keyboard? It almost works perfectly but I haven't had any luck with autofractions for example. Codemirror seems to correctly identify the keypresses like / and Tab key despite it not working (I tried it in codemirror.net/try).

**Comment by henusys** [comment]
latex suite is a great plugin, but unfortunately it doesn't work on mobile. Are you considering adding mobile support when using IME input methods such as Gboard. Thank you very much. @artisticat1

**Comment by oldkingOK** [comment]
@TomBPotochek  Sorry for the late reply. I just try it. It's quite strange that the physical keyboard works well with autofractions while the codeboard doesn't work. The reason might be the symbol "/" on the codeboard can be customized, which probably means that only symbols on codeboard use IME.
I have forked gazlaws-dev/codeboard and plan to working on it for a few days. Thank you very much!

**Comment by oldkingOK** [comment]
@TomBPotochek Finished, click [here](https://github.com/oldkingOK/codeboard-for-obsidian-latex-plugin/releases/tag/test) to download and have a try. ![Screenrecorder-2023-09-09-15-26-56-111.gif](https://github.com/artisticat1/obsidian-latex-suite/assets/30453803/d00fd49b-9adf-454c-918b-a7f307cb75ec)

**Comment by TomBPotochek** [comment]
@oldkingOK great, it works! I see it was a fairly simple change. I would not have known.

Now this just needs to be done for the other symbols and the problem is solved completely (eg. `<<` expand to `\ll`, a snippet I use that expands `a*b` to `a \cdot b`, etc).  
I might add it to your repo as a PR ...If I can figure out how to build an android app in my computer 😵

**Comment by pikatwinky** [comment]
@TomBPotochek you're a lifesaver, thanks for the suggestion about using codeboard. 

@oldkingOK Thank you so much for share that build of the app

It's such a shame that that keyboard doesn´t recieve support anymore, i hope it doesn't break very soon.

**Comment by artisticat1** [comment]
It should be possible to handle IME input - for reference, [here's how the vim CM6 plugin handles it](https://github.com/replit/codemirror-vim/blob/2f871797743a46628155477bae18f2f3f88a3c44/src/index.ts#L280). Any PRs for this would be welcome.

**Comment by oldkingOK** [comment]
> It should be possible to handle IME input - for reference, [here's how the vim CM6 plugin handles it](https://github.com/replit/codemirror-vim/blob/2f871797743a46628155477bae18f2f3f88a3c44/src/index.ts#L280). Any PRs for this would be welcome.

Thanks for the helpful advice! I have modified some [code](https://github.com/oldkingOK/obsidian-latex-suite) and it works well with my device with system default keyboard using 'letter mode', but for some unknown reason it doesn't work with keyboard using 'word mode'. It still needs to be test and debug. 

Test environment:
- Redmi Note 9 Pro
- Android 12
- Sogou Keyboard
![Screenrecorder-2023-09-16-21-50-32-22](https://github.com/artisticat1/obsidian-latex-suite/assets/30453803/3bc10f4d-edfc-4190-90c9-7ebe749f2618)

**Comment by artisticat1** [comment]
> Thanks for the helpful advice! I have modified some [code](https://github.com/oldkingOK/obsidian-latex-suite) and it works well with my device with system default keyboard using 'letter mode', but for some unknown reason there're still some bugs using 'word mode'. It still needs to be test and debug.

Great! Feel free to open a PR to discuss. I don't have an android device, so I can't help debug very much. What do you mean by "word mode"?

**Comment by oldkingOK** [comment]
> > Thanks for the helpful advice! I have modified some [code](https://github.com/oldkingOK/obsidian-latex-suite) and it works well with my device with system default keyboard using 'letter mode', but for some unknown reason there're still some bugs using 'word mode'. It still needs to be test and debug.
> 
> Great! Feel free to open a PR to discuss. I don't have an android device, so I can't help debug very much. What do you mean by "word mode"?

Sorry for my improper description. The "word mode" is a function that the keyboard  can give word suggestions after every key input like the screenshot below.

![Screenshot_2023-09-16-23-53-51-839_com.github.android.png](https://github.com/artisticat1/obsidian-latex-suite/assets/30453803/926b1a07-3c89-4802-8827-4cd965f24adb)

**Comment by henusys** [comment]
@oldkingOK ，Yes，It works, but the 'tab' key is does't work when using the external keyboard.

**Comment by oldkingOK** [comment]
@henusys , the 'tab' key work fine with my external keyboard.
- Can you give more details about it? such as Android version, external keyboard brand and model, system default keyboard etc.
- It would be quite helpful if you can provide a screen record or a more detailed description such as how the cursor moves after tab etc.
- Could you install the [debug version I just compile](https://github.com/oldkingOK/obsidian-latex-suite/releases/tag/debug) and this dev tools plugin (https://github.com/KjellConnelly/obsidian-dev-tools) ? This will give us access to a console on mobile. After enabling the plugin, open a console using the Command palette. Type something and 'Tab' then screenshot the output in the console.

**Comment by henusys** [comment]
Android version is MIUI 12.5.2, 
IME:  sougou 
External keyboard: LEICKE

If I  use the codeboard input method, everything works well. But when using sougou input, '\alpha' '\beta' '\frac' and so on could be triggered well, while for the triggered '\frac{}{}'  the tab key  just reponse the tab and isn't move the cursor to the next brace.

**Comment by oldkingOK** [comment]
@henusys ,It work well with my devices,
Android version is MIUI 14.0.2
IME: sogou
External keyboard: INPHIC

<img src="https://github.com/artisticat1/obsidian-latex-suite/assets/30453803/66d8bd64-3923-4823-93d9-0c774489db89" width = 216 height = 480/>

- Are you using the default snippets?
- The external keyboard might need switch to "android mode
<img src="https://github.com/artisticat1/obsidian-latex-suite/assets/30453803/d403dc6e-cf51-42f5-8a6f-df92b95ca91f" width = 200 height = 200/>

If it still doesn't work, I will appreciate it if you could help me debug through the way above.

> * Could you install the [debug version I just compile](https://github.com/oldkingOK/obsidian-latex-suite/releases/tag/debug) and this dev tools plugin (https://github.com/KjellConnelly/obsidian-dev-tools) ? This will give us access to a console on mobile. After enabling the plugin, open a console using the Command palette. Type something and 'Tab' then screenshot the output in the console.

**Comment by henusys** [comment]
yes，thank you very much. I test it as follows:
![6c6c802e192f706edfc10002b7bacc2](https://github.com/artisticat1/obsidian-latex-suite/assets/9565297/72b0d007-3e37-4360-893b-ffc33b7c8989)
![777622cedd992e6d219f91b42b89803](https://github.com/artisticat1/obsidian-latex-suite/assets/9565297/5f294dc9-dddd-4751-9695-3cd3fadf08e6)

The obsidian mobile version is V1.4.8

**Comment by oldkingOK** [comment]
@henusys Thanks! It seems that the app recognizes the tab as a text '\t' instead of a key. I have edited and compiled a new [one](https://github.com/oldkingOK/obsidian-latex-suite/releases/tag/debug-2), you could have a try.
If it still doesn't work, screenshot the console output again.

**Comment by henusys** [comment]
Yes I test it just now. once I type 'mk' or 'dm' to trigger the math mode, the error console will appear similar message as follows:
```
"(http://localhost/app.js:1:490958)at pc
(http://localhost/app.js:1 :477936)at e.flush(http://localhost/app.js:1:486330)
at MutationObserver .<anonymous>(http://localhost/app.js :1:479128)" 
```
and 
```
"Unidentified Key detected". At this time the tab key will be failure. 
```

But if I quit the current edite, and then directly select to edit the mathematical formula by touch screen, not use 'mk' to trigger math mode, the error message will not appear and tab key also working well.

**Comment by oldkingOK** [comment]
> Yes I test it just now. once I type 'mk' or 'dm' to trigger the math mode, the error console will appear similar message as follows:
> 
> ```
> "(http://localhost/app.js:1:490958)at pc
> (http://localhost/app.js:1 :477936)at e.flush(http://localhost/app.js:1:486330)
> at MutationObserver .<anonymous>(http://localhost/app.js :1:479128)" 
> ```
> 
> and
> 
> ```
> "Unidentified Key detected". At this time the tab key will be failure. 
> ```
> 
> But if I quit the current edite, and then directly select to edit the mathematical formula by touch screen, not use 'mk' to trigger math mode, the error message will not appear and tab key also working well.

Thats a little strange, is there any messages like "Get text xxx from.. to.." after tab key pressed?

**Comment by henusys** [comment]
Yes it have! May be, I got the reason why, if I using the MIUI custom Sogou input method isn't the latest Sougou app,  it will be work well. 
But I confused that there is an error message every time latex suite triggered. just like this 
![03d360afbc7e5d40b131aad6f2d7b53](https://github.com/artisticat1/obsidian-latex-suite/assets/9565297/b3c1d6a9-c96a-4f86-93c1-8dc9d29e9110)

**Comment by oldkingOK** [comment]
> Yes it have! May be, I got the reason why, if I using the MIUI custom Sogou input method isn't the latest Sougou app, it will be work well. But I confused that there is an error message every time latex suite triggered. just like this.

So, it means that the latest Sogou keyboard will cause problems while the sogou keyboard custemized for MIUI works fine? 

> But I confused that there is an error message every time latex suite triggered. just like this.

Yes, I have noticed that and plan to figure it out after solving other main issues.

**Comment by henusys** [comment]
Yes you are right, thank you very much.

**Comment by oldkingOK** [comment]
You're welcome. And thanks for your testing.

**Comment by IEatCodeDaily** [comment]
Having similar problem. Using Obsidian 1.4.9 on Samsung Galaxy Tab S6 running Android 12 and oneUI 4.1.1.

Snippets doesn't work at all on Gboard and Swiftkey. The weird thing is when I use Samsung Keyboard. Any snippet is injected twice with some weird behaviour on how $0 is handled as shown below.
![Screenshot_20231002_121612_Obsidian](https://github.com/artisticat1/obsidian-latex-suite/assets/68648097/bc310153-3fd3-4c02-8cb3-851d18992ea2)

I can't try codeboard because it's apparently not compatible with my tablet.
I'll try it on my phone. Will update on it later.

**Comment by IEatCodeDaily** [comment]
Okay apparently the "bug" on the Samsung Keyboard I've shown above was caused by make.md plugins.
Now I don't know what I should do...
Do I make an issue for a bug in this plugins or in make.md?

Because this bug only happen on mobile. Obsidian on my PC doesn't have this problem at all.

**Comment by awsharif** [comment]
HI @IEatCodeDaily,

I cannot seem to get LaTeX suite working with a similar arrangements - I am on One UI 5.1 on a Z Fold 4 using stock samsung keyboard. Could you share your settings for the samsung keyboard?

Thanks!

**Comment by IEatCodeDaily** [comment]
Ah sorry, I forgot to mention that I'm using the physical keyboard. Without the physical keyboard I'm also unable to get LaTeX suite working no matter what.

**Comment by Mr-Moocoo** [comment]
I have also just started getting this issue. It used to work fine on my Samsung galaxy tab s8. However it stopped working recently (i believe after i updated the os).
Upon disabling the predictive text feature in Samsung keyboard in settings the plugin works fine as well as other obsidian features. 

Not sure if this helps but it works as a temporary solution.

**Comment by JavenQvQ** [comment]
> 完成后，[单击此处](https://github.com/oldkingOK/codeboard-for-obsidian-latex-plugin/releases/tag/test)下载并尝试。![Screenrecorder-2023-09-09-15-26-56-111.gif](https://private-user-images.githubusercontent.com/30453803/266767254-d00fd49b-9adf-454c-918b-a7f307cb75ec.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2NDQwODksIm5iZiI6MTczMDY0Mzc4OSwicGF0aCI6Ii8zMDQ1MzgwMy8yNjY3NjcyNTQtZDAwZmQ0OWItOWFkZi00NTRjLTkxOGItYTdmMzA3Y2I3NWVjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDE0MjMwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0ZjM1ZjNkOWVhYWFjNzVmN2U4YzUzNWJhZDdhZjEyOTk4OGQ0Zjg0MzYyNGQ2OWIxOTk2MGFkN2EwOTVlZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aX4qjRlyxCJNGJ2F335BGv1hcfOQuJA07j_koN6LHbA) [ ![Screenrecorder-2023-09-09-15-26-56-111.gif](https://private-user-images.githubusercontent.com/30453803/266767254-d00fd49b-9adf-454c-918b-a7f307cb75ec.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2NDQwODksIm5iZiI6MTczMDY0Mzc4OSwicGF0aCI6Ii8zMDQ1MzgwMy8yNjY3NjcyNTQtZDAwZmQ0OWItOWFkZi00NTRjLTkxOGItYTdmMzA3Y2I3NWVjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDE0MjMwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0ZjM1ZjNkOWVhYWFjNzVmN2U4YzUzNWJhZDdhZjEyOTk4OGQ0Zjg0MzYyNGQ2OWIxOTk2MGFkN2EwOTVlZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aX4qjRlyxCJNGJ2F335BGv1hcfOQuJA07j_koN6LHbA) ](https://private-user-images.githubusercontent.com/30453803/266767254-d00fd49b-9adf-454c-918b-a7f307cb75ec.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2NDQwODksIm5iZiI6MTczMDY0Mzc4OSwicGF0aCI6Ii8zMDQ1MzgwMy8yNjY3NjcyNTQtZDAwZmQ0OWItOWFkZi00NTRjLTkxOGItYTdmMzA3Y2I3NWVjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDE0MjMwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0ZjM1ZjNkOWVhYWFjNzVmN2U4YzUzNWJhZDdhZjEyOTk4OGQ0Zjg0MzYyNGQ2OWIxOTk2MGFkN2EwOTVlZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aX4qjRlyxCJNGJ2F335BGv1hcfOQuJA07j_koN6LHbA) [ ](https://private-user-images.githubusercontent.com/30453803/266767254-d00fd49b-9adf-454c-918b-a7f307cb75ec.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2NDQwODksIm5iZiI6MTczMDY0Mzc4OSwicGF0aCI6Ii8zMDQ1MzgwMy8yNjY3NjcyNTQtZDAwZmQ0OWItOWFkZi00NTRjLTkxOGItYTdmMzA3Y2I3NWVjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDE0MjMwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0ZjM1ZjNkOWVhYWFjNzVmN2U4YzUzNWJhZDdhZjEyOTk4OGQ0Zjg0MzYyNGQ2OWIxOTk2MGFkN2EwOTVlZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aX4qjRlyxCJNGJ2F335BGv1hcfOQuJA07j_koN6LHbA)

这个链接失效了,请问现在还有解决方法吗

**Comment by pikatwinky** [comment]
@JavenQvQ Here is the file, its the same he uploaded. It seems he just deleted his repo
[app-signed.zip](https://github.com/user-attachments/files/17673204/app-signed.zip)

**Comment by johnsidi77** [comment]
I have a TCL NEXTPaper 14 Android tablet. After much time, experimentation, and frustration, I finally managed to activate my snippets from an external keyboard using the Android app [Unexpected Keyboard](https://play.google.com/store/apps/details?id=juloo.keyboard2&hl=en&pli=1). The Hacker's Keyboard, which I use on my Motorola phone (Android 12), did not work!

Additionally, I encountered the issue that Google does not provide an option to uninstall or deactivate the Gboard keyboard on Android 14. Unexpectedly, the app [Keyboard Switcher](https://play.google.com/store/apps/details?id=com.kunzisoft.keyboard.switcher&hl=en) allowed me to do exactly that.

As a result, the plugin now works just fine with an external keyboard. However, the snippets still cannot be expanded using the virtual keyboard.

**Comment by oldkingOK** [comment]
I have been using Latex-Suite for more than a year now and it helps a lot, thanks a lot to all the maintainers of this repo.

I've updated the previous code and after testing with my device, the following keyboards have been supported nicely, including virtual and external keyboards, and there is no need to turn off the word completion.

- Gboard
- Sogou keyboard, including MIUI version and general version
- MS Swift

You can try the plugin I compiled at [Releases/1.9.7-dev](https://github.com/oldkingOK/obsidian-latex-suite/releases/tag/1.9.7-dev), I would like to get feedback from you guys on testing it :)

**Important:** You need to turn off `Don't trigger snippets when IME is active` at the bottom of the Latex Suite settings. Because most mobile devices have IME-based input, Latex Suite cannot be triggered without turning it off.

**Comment by oldkingOK** [comment]
Hi @johnsidi77 , I only have two android device and my code still needs more testing, can you try it? I'd appreciate it.

**Comment by pigi5** [comment]
+1 to this. Using Microsoft SwiftKey or Gboard and snippets don't work with the Space or Tab option.

**Comment by oldkingOK** [comment]
Hi, @pigi5 
Can you try this version ([Release/1.9.7-dev](https://github.com/oldkingOK/obsidian-latex-suite/releases/tag/1.9.7-dev)) of Latex Suite that I'm fixing? Just download the main.js and put it in .obsidian/plugins/obsidian-latex-suite, and turn off `Don't trigger snippets when IME is active` at the bottom of the Latex Suite settings.

**Comment by pigi5** [comment]
@oldkingOK I'd be happy to help out but honestly I have no idea how to move a downloaded file into an app's storage on my phone and Google isn't helping much. Would I need root or a connected computer to do that?

**Comment by oldkingOK** [comment]
@pigi5 Thanks for your feedback! Can you install the debug version ([Release/1.9.7-debug](https://github.com/oldkingOK/obsidian-latex-suite/releases/tag/1.9.7-debug)) I just compile and a dev tools plugin (https://github.com/KjellConnelly/obsidian-dev-tools) ? This will give us access to a console on mobile. The full tutorial of the dev tool is [here](https://github.com/KjellConnelly/obsidian-dev-tools/issues/8). After enabling the plugin, open a console using the Command palette. Type something and 'Tab' then screenshot the output in the console.

**Comment by liuyun1993** [comment]
@oldkingOK  It works for me. My device is Xiaomi 6S Pro and the keyboard is Sogou keyboard.

**Comment by golgothas-Terror** [comment]
I'm using a Lenovo N22 Chromebook running the android version of Obsidian with the built-in physical keyboard. Snippets weren't working on the main version, but they work smoothly on 1.9.7-dev with IME setting off.

**Comment by van-zxc** [comment]
@liuyun1993 hey! I use xiaomi 6S pro too. I just tried baidu keyboard and it magically worked. oh my gosh

**Comment by vaibhav423** [comment]
@oldkingOK The Jan 13 1.9.7 debug build worked for me , tested on ms swift keyboard , gboard , unexpected keyboard

**Comment by LimeBlogs** [comment]
> Hi, [@pigi5](https://github.com/pigi5) Can you try this version ([Release/1.9.7-dev](https://github.com/oldkingOK/obsidian-latex-suite/releases/tag/1.9.7-dev)) of Latex Suite that I'm fixing? Just download the main.js and put it in .obsidian/plugins/obsidian-latex-suite, and turn off `Don't trigger snippets when IME is active` at the bottom of the Latex Suite settings.

You are a Hero!!! It really worked!!!

**Comment by zitons** [comment]
@oldkingOK Thanks for your contribution.Wish for merge.
